// Constants for Flashcard content generation
export const FLASHCARD_GENERATE_REQUEST = 'FLASHCARD_GENERATE_REQUEST';
export const FLASHCARD_GENERATE_SUCCESS = 'FLASHCARD_SUCCESS';
export const FLASHCARD_GENERATE_FAIL = 'FLASHCARD_FAIL';

export const FLASHCARD_LIST_REQUEST = "FLASHCARD_LIST_REQUEST";
export const FLASHCARD_LIST_SUCCESS = "FLASHCARD_LIST_SUCCESS";
export const FLASHCARD_LIST_FAIL = "FLASHCARD_LIST_FAIL";  // Add this one

export const FLASHCARD_DETAILS_REQUEST = "FLASHCARD_DETAILS_REQUEST";
export const FLASHCARD_DETAILS_SUCCESS = "FLASHCARD_DETAILS_SUCCESS";
export const FLASHCARD_DETAILS_FAIL = "FLASHCARD_DETAILS_FAIL"; // Add this one

export const FLASHCARD_DELETE_REQUEST = "FLASHCARD_DELETE_REQUEST";
export const FLASHCARD_DELETE_SUCCESS = "FLASHCARD_DELETE_SUCCESS";
export const FLASHCARD_DELETE_FAIL = "FLASHCARD_DELETE_FAIL";
