// Constants for OpenAI content generation
export const OPENAI_GENERATE_REQUEST = 'OPENAI_GENERATE_REQUEST';
export const OPENAI_GENERATE_SUCCESS = 'OPENAI_GENERATE_SUCCESS';
export const OPENAI_GENERATE_FAIL = 'OPENAI_GENERATE_FAIL';
