export const GENERATE_QUIZ_REQUEST = "GENERATE_QUIZ_REQUEST";
export const GENERATE_QUIZ_SUCCESS = "GENERATE_QUIZ_SUCCESS";
export const GENERATE_QUIZ_FAIL = "GENERATE_QUIZ_FAIL";

export const QUIZ_LIST_REQUEST = "GENERATE_QUIZ_REQUEST";
export const QUIZ_LIST_SUCCESS = "GENERATE_QUIZ_SUCCESS";
export const QUIZ_LIST_FAIL = "GENERATE_QUIZ_FAIL";

export const QUIZ_DISPLAY_REQUEST = "QUIZ_DISPLAY_REQUEST";
export const QUIZ_DISPLAY_SUCCESS = "QUIZ_DISPLAY_SUCCESS";
export const QUIZ_DISPLAY_FAIL = "QUIZ_DISPLAY_FAIL";

export const GET_QUIZZES_REQUEST = 'GET_QUIZZES_REQUEST';
export const GET_QUIZZES_SUCCESS = 'GET_QUIZZES_SUCCESS';
export const GET_QUIZZES_FAIL = 'GET_QUIZZES_FAIL';

export const SUBMIT_QUIZ_REQUEST = 'SUBMIT_QUIZ_REQUEST';
export const SUBMIT_QUIZ_SUCCESS = 'SUBMIT_QUIZ_SUCCESS';
export const SUBMIT_QUIZ_FAIL = 'SUBMIT_QUIZ_FAIL';

export const GET_QUIZ_RESULT_REQUEST = 'GET_QUIZ_RESULT_REQUEST';
export const GET_QUIZ_RESULT_SUCCESS = 'GET_QUIZ_RESULT_SUCCESS';
export const GET_QUIZ_RESULT_FAIL = 'GET_QUIZ_RESULT_FAIL';
