// Ensure these constants are properly exported
export const STUDY_NOTE_LIST_REQUEST = 'STUDY_NOTE_LIST_REQUEST';
export const STUDY_NOTE_LIST_SUCCESS = 'STUDY_NOTE_LIST_SUCCESS';
export const STUDY_NOTE_LIST_FAIL = 'STUDY_NOTE_LIST_FAIL';

export const STUDY_NOTE_DELETE_REQUEST = 'STUDY_NOTE_DELETE_REQUEST';
export const STUDY_NOTE_DELETE_SUCCESS = 'STUDY_NOTE_DELETE_SUCCESS';
export const STUDY_NOTE_DELETE_FAIL = 'STUDY_NOTE_DELETE_FAIL';


